name: _snld3d
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Packaging
  - pip
  - python-semantic-release
  # Package
  - python >=3.9.9,<3.11
  - brotlipy =0.7.*
  - geopandas-base =0.10.*
  - jinja2 =3.1.*
  - netCDF4 =1.5.*
  - numpy =1.22.*,>=1.21
  - pandas =1.4.*
  - pyyaml =6.*
  - scipy =1.8.*
  - shapely =1.8.*
  - tabulate =0.8.*
  - xarray =2022.3.*,>=0.20.1
  # Testing
  - mypy
  - pytest
  - pytest-cov
  - pytest-mock
  - tox-conda
  # Documentation
  - git
  - sphinx
  - sphinx-autodoc-typehints
  - pip:
    - insipid-sphinx-theme
    - https://github.com/Holzhaus/sphinx-multiversion/archive/refs/heads/master.zip
