name: _snld3d
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Package
  - python>=3.9.9,<3.10
  - pip
  - brotlipy
  - geopandas-base
  - jinja2
  - netCDF4
  - numpy>=1.21
  - pandas
  - pyyaml
  - scipy
  - shapely
  - tabulate
  - xarray>=0.20.1
  # Testing
  - mypy
  - pytest
  - pytest-mock
  - tox-conda
  # Documentation
  - sphinx
  - sphinx-autodoc-typehints
  - pip:
    - insipid-sphinx-theme
