name: _snld3d
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9.9,<3.10
  - pip
  - brotlipy
  - geopandas-base
  - jinja2
  - netCDF4
  - numpy>=1.21
  - pandas
  - pyyaml
  - scipy
  - shapely
  - tabulate
  - xarray>=0.20.1
