name: Continuous Integration Tests
on: [push, pull_request]
jobs:
  pytest:
    name: Unit Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.9']
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: _snld3d
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - run: |
          conda info
      - name: Install package
        run: |
          pip install --no-deps -e .
      - name: Run tests
        run: |
          conda install -y pytest pytest-cov pytest-mock
          pytest --cov --cov-config=setup.cfg --cov-report=xml tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
            fail_ci_if_error: true
