name: Semantic Release

on:
  push:
    branches:
      - conda_recipe

jobs:
  release:
    name: Publish the package
    runs-on: ubuntu-latest
    env:
      conda-directory: ${{ github.workspace }}/.conda
    if: github.repository == 'H0R5E/SNL-Delft3D-CEC-Verify'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.ADMIN_TOKEN }}
    - name: Expose git commit data
      uses: rlespinasse/git-commit-data-action@v1
    - name: Wait for tests to succeed
      uses: lewagon/wait-on-check-action@v1.0.0
      with:
        ref: ${{ github.ref }}
        running-workflow-name: 'Publish the package'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        wait-interval: 10
      if: env.GIT_COMMIT_COMMITTER_NAME != 'github-actions'
    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.ADMIN_TOKEN }}
      if: env.GIT_COMMIT_COMMITTER_NAME != 'github-actions'
