name: Static Type Checks
on: [push, pull_request]
jobs:
  mypy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: ['3.9']
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: 'true'
      - uses: actions/cache@v2
        with:
          path: .mypy_cache
          key: ${{ runner.os }}-mypy-${{ hashFiles('setup.cfg') }}
          restore-keys: ${{ runner.os }}-mypy
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: _snld3d
          environment-file: .conda/environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
      - run: |
          conda info
      - name: Install package
        run: |
          pip install --no-deps -e .
      - name: Run checks
        run: |
          mypy --install-types --non-interactive src
  status:
    name: Static Type Checks
    runs-on: ubuntu-latest
    needs: mypy
    steps:
      - run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "Static Type Checks",
            "state": "success",
            "description": "Static type checks passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
